name: absen_marsa
description: Aplikasi Absensi MARSA - SMK Ma'arif 9 Kebumen

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Local cache & storage
  sqflite: ^2.3.3
  path: ^1.9.0

  # GPS
  geolocator: ^11.0.0
  
  # Kamera & Face
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.11.0
  
  # Image picker
  image_picker: ^1.0.7
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  
  # Konversi Hijriah
  hijri: ^2.0.3

# Shared preferences sudah ada (untuk foto profil lokal)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/
